modLoader="javafml"
loaderVersion="[4,)"
license="Apache License version 2.0"

[[mods]]
modId="bettercreeper"
version="1.0.1"
displayName="Better Creeper"
displayURL="https://youtube.com/@StudiCraft"
logoFile="logo.png"
credits="Nothing To Show"
authors="StudiCraft"
description="Enhances creepers with a dramatic 3-stage color progression (green \u2192 orange \u2192 red) during their fuse sequence. Each phase features multiple texture variants for smooth visual transitions, making explosive encounters more intense and visually engaging. Client-side only, performance optimized."

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.bettercreeper]]
    modId="neoforge"
    type="required"
    versionRange="[21.4.137,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.bettercreeper]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.4]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration